### PR TITLE
added support for Duck Duck go

### PR DESCRIPTION
**Pull request by akshaynikhare**
added support for Duck Duck go 

duckduckgo engine

### CODE REVIEW

**Comment by pipboy96** [comment]
DuckDuckGo gets results from Bing.

**Comment by akshaynikhare** [comment]
> DuckDuckGo gets results from Bing.

is that so.

**Comment by pipboy96** [comment]
@akshaynikhare Compare returned results.

**Comment by pipboy96** [comment]
@akshaynikhare https://duck.co/help/results/sources

> We also of course have more traditional links in the search results, which we also source from a variety of partners, including Oath (formerly Yahoo) and Bing.

Russian results are also sourced from Yandex.

**Comment by akshaynikhare** [comment]
so i think we should work to include Yandex

**Pull request closed without merging**
