### PR TITLE
Modularized code and generally cleaned things up

### PR DESCRIPTION
**Pull request by Plazmaz**
Hooray for not slamming everything into one file!

### CODE REVIEW

**Comment by Plazmaz** [comment]
Any response to this @aboul3la?

**Comment by timofonic** [comment]
Hello. Any news? I'm interested on this :D 


@Plazmaz 

If he doesn't reply, just make a fork in the meantime with other interesting pull requests and forks so we can enjoy it :D 

What about
https://github.com/secynic/ipwhois
https://github.com/hyasinfosec/python-whois

Both suffer forking hell somewhat too :(

**Comment by Plazmaz** [comment]
@timofonic way ahead of you https://github.com/Plazmaz/Sublist3r

**Comment by akkatracker** [comment]
It's a shame it has to come down to all these forks. @aboul3la I would be happy to help administer this repo (as would a bunch of other people).

**Comment by Plazmaz** [comment]
Agreed @akkatracker. If we don't get a response here, I'll just maintain my fork

**Comment by aboul3la** [comment]
Hey @Plazmaz, 

I'm sorry for the delayed response on this PR. I appreciate your efforts and your contributions. 

I been working on the new version of Sublist3r where I'm going to build Modularized code with a different concept, So it will be easier for everyone to push their own plugins / feeds to Sublist3r.

But I would like to thank you for PR and your can maintain your fork, I'm sure it will be helpful for many people.

**Pull request closed without merging**
