### PR TITLE
Python3 compatibility

### PR DESCRIPTION
**Pull request by gloomy-ghost**
I just used 2to3. Please tell me if anything goes wrong.

Close: #39

### CODE REVIEW

**Comment by gloomy-ghost** [comment]
Removing `Queue` since sublist3r.py is not using it.

**Comment by aboul3la** [comment]
Thanks for your PR. 
Seems it has some conflicts now. Can you please resolve the conflicts so i can review the code after that.
Thanks

**Comment by gloomy-ghost** [comment]
Thanks for responding, I think it is resolved by now.

**Comment by gloomy-ghost** [comment]
Conflicts again due to https://github.com/aboul3la/Sublist3r/commit/ec4251ad47c59c820137b5d2cd98b885228696c5, I will rebase this PR later.

**Comment by the-st0rm** [comment]
Sorry man has to push the latest updates. Once you fix the conflicts, create a PR and I will merge it ^^

Cheers

**Comment by gloomy-ghost** [comment]
@the-st0rm I'm sorry too because I just discovered that I linked to a wrong commit...

**Comment by gloomy-ghost** [comment]
Fixed

**Comment by the-st0rm** [comment]
Thanks :+1: 
Merged ^^

**Comment by gloomy-ghost** [comment]
Thanks. Should we also update the README?

**Comment by aboul3la** [comment]
Thanks @gloomy-ghost for your PR, there was a little bug in write_file() function with the python3 compatibility. I just pushed a fix for it in commit 376959e1c4242b4bdb64abd7f8c5a876325a96b3, so now Sublist3r should works fine with Python3. 

I will update the README shortly.

**Pull request merged**
