### PR TITLE
 bannergrabber.py

### PR DESCRIPTION
**Pull request by Verondrummond171**
For improvement

### CODE REVIEW

**Comment by aboul3la** [comment]
Hi @Verondrummond171,

I don't see a need for this code in Sublist3r, as the tool is designed only to perform subdomains enumeration, also your code doesn't do anything rather than establishing a simple TCP socket which could be done using netcat or other similar tools.

I will close this now.

**Comment by Verondrummond171** [comment]
Can a
I make something better and more powerful

**Comment by Verondrummond171** [comment]
Like a information gathering to that is more powerful than other scanners

**Comment by Verondrummond171** [comment]
And more a powerful bug bounty tool

**Pull request closed without merging**
